// <auto-generated />
using System;
using IlabAuthentication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IlabAuthentication.Migrations
{
    [DbContext(typeof(AuthenticationDbContext))]
    [Migration("20250726110047_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IlabAuthentication.Data.Models.ApplicationRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Member")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ConcurrencyStamp = "1fbd204a-762b-4149-9a54-44ae6354d79c",
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Name = "root",
                            NormalizedName = "ROOT"
                        },
                        new
                        {
                            Id = 2L,
                            ConcurrencyStamp = "26E9A03B-E6BB-4567-A36B-E1DE6B6C1227",
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Name = "Super Admin",
                            NormalizedName = "SUPER"
                        },
                        new
                        {
                            Id = 3L,
                            ConcurrencyStamp = "d3dff883-d8ba-4f25-8529-29ef5f5343ce",
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 4L,
                            ConcurrencyStamp = "c78c489a-fb53-4a42-aee6-60818a3be800",
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("IlabAuthentication.Data.Models.ApplicationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disable")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Member")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Theme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ParentId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a7e26408-644a-48ca-a0a7-7cb94e41315d",
                            Disable = false,
                            Email = "root",
                            EmailConfirmed = true,
                            FirstName = "Root",
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            LastName = "",
                            LockoutEnabled = false,
                            Member = "root",
                            NormalizedEmail = "ROOT",
                            NormalizedUserName = "ROOT",
                            PasswordHash = "AQAAAAIAAYagAAAAELjslJJId5s/CZUdXozgD3Pr7IbgTUn+CiLkN8o1sf2+WTJWizU2wDKXb/IPyW35/Q==",
                            PhoneNumber = "0000",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3DMLAIZXSOSRUJWEQ2R7NTE7NGAAQYBA",
                            TwoFactorEnabled = false,
                            UserName = "root"
                        },
                        new
                        {
                            Id = 2L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e6ac56cd-cb41-4059-b979-a0d7a7ac5fe0",
                            Disable = false,
                            Email = "super@zorya.co.in",
                            EmailConfirmed = true,
                            FirstName = "Super",
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            Member = "root",
                            NormalizedEmail = "SUPER@ZORYA.CO.IN",
                            NormalizedUserName = "SUPER",
                            ParentId = 1L,
                            PasswordHash = "AQAAAAIAAYagAAAAELjslJJId5s/CZUdXozgD3Pr7IbgTUn+CiLkN8o1sf2+WTJWizU2wDKXb/IPyW35/Q==",
                            PhoneNumber = "0000",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3DMLAIZXSOSRUJWEQ2R7NTE7NGAAQYBA",
                            TwoFactorEnabled = false,
                            UserName = "super@zorya.co.in"
                        });
                });

            modelBuilder.Entity("IlabAuthentication.Data.Models.Privilege", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Member")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Privileges");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "user",
                            Name = "add",
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "user",
                            Name = "edit",
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "user",
                            Name = "delete",
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "user",
                            Name = "view",
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "user",
                            Name = "list",
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "role",
                            Name = "add",
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "role",
                            Name = "edit",
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "role",
                            Name = "delete",
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "role",
                            Name = "view",
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "role",
                            Name = "list",
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 11L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "user",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 12L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "user",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 13L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "user",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 14L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "user",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 15L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "user",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 16L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "role",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 17L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "role",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 18L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "role",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 19L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "role",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 20L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "role",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 21L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "enterprise",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 22L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "enterprise",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 23L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "enterprise",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 24L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "enterprise",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 25L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "enterprise",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 26L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "businessunit",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 27L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "businessunit",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 28L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "businessunit",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 29L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "businessunit",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 30L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "businessunit",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 31L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "vendor",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 32L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "vendor",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 33L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "vendor",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 34L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "vendor",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 35L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "vendor",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 36L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "purchaseorder",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 37L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "purchaseorder",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 38L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "purchaseorder",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 39L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "purchaseorder",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 40L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "purchaseorder",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 41L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "purchaseorderitem",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 42L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "purchaseorderitem",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 43L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "purchaseorderitem",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 44L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "purchaseorderitem",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 45L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "purchaseorderitem",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 46L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "grn",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 47L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "grn",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 48L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "grn",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 49L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "grn",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 50L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "grn",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 51L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "grnitem",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 52L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "grnitem",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 53L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "grnitem",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 54L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "grnitem",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 55L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "grnitem",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 56L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "indent",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 57L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "indent",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 58L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "indent",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 59L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "indent",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 60L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "indent",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 61L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "indentitem",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 62L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "indentitem",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 63L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "indentitem",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 64L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "indentitem",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 65L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "indentitem",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 66L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "itemmaster",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 67L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "itemmaster",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 68L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "itemmaster",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 69L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "itemmaster",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 70L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "itemmaster",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 71L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "store",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 72L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "store",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 73L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "store",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 74L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "store",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 75L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "store",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 76L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "stockentry",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 77L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "stockentry",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 78L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "stockentry",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 79L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "stockentry",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 80L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "stockentry",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 81L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "stockconsumption",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 82L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "stockconsumption",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 83L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "stockconsumption",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 84L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "stockconsumption",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 85L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "stockconsumption",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 86L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "stockadjustment",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 87L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "stockadjustment",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 88L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "stockadjustment",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 89L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "stockadjustment",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 90L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "stockadjustment",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 91L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "category",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 92L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "category",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 93L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "category",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 94L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "category",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 95L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "category",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 96L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "unitofmeasure",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 97L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "unitofmeasure",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 98L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "unitofmeasure",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 99L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "unitofmeasure",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 100L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "unitofmeasure",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 101L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "testmaster",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 102L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "testmaster",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 103L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "testmaster",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 104L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "testmaster",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 105L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "testmaster",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 106L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "testparameter",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 107L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "testparameter",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 108L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "testparameter",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 109L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "testparameter",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 110L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "testparameter",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 111L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "specimenmaster",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 112L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "specimenmaster",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 113L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "specimenmaster",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 114L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "specimenmaster",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 115L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "specimenmaster",
                            Name = "list",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 116L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "department",
                            Name = "add",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 117L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "department",
                            Name = "edit",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 118L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "department",
                            Name = "delete",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 119L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "department",
                            Name = "view",
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 120L,
                            Key = "1536B022-C5C9-4358-BB6A-466F2075B7D4",
                            Member = "root",
                            Module = "department",
                            Name = "list",
                            RoleId = 2L
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            RoleId = 1L
                        },
                        new
                        {
                            UserId = 2L,
                            RoleId = 2L
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IlabAuthentication.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("IlabAuthentication.Data.Models.ApplicationUser", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("IlabAuthentication.Data.Models.Privilege", b =>
                {
                    b.HasOne("IlabAuthentication.Data.Models.ApplicationRole", "Role")
                        .WithMany("Privileges")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("IlabAuthentication.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("IlabAuthentication.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("IlabAuthentication.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("IlabAuthentication.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IlabAuthentication.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("IlabAuthentication.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IlabAuthentication.Data.Models.ApplicationRole", b =>
                {
                    b.Navigation("Privileges");
                });
#pragma warning restore 612, 618
        }
    }
}
